## Data frames: Group of series

In [ ]:
#Creating a data frame

In [1]:
import numpy as numpy
import pandas as pd

In [5]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
} #dictionary of key-value pairs
df = pd.DataFrame(data) #group of series
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [7]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns) #using custom column name
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#Selection and indexing of columns

In [11]:
df2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [12]:
df2[["Name", "City"]] #accessing multiple row column at a time

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [ ]:
#Creating a new column

In [21]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

In [14]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [ ]:
#removing column

In [15]:
df2.drop("Designation", axis= 1) #this doesn't works in inplace i.e this creates a copy

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [22]:
df2.drop("Designation", axis=1, inplace=True) #in-place column removal
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
df2.drop(0, axis= 0) #row can be delete by using axis = 0

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [ ]:
#selecting a row

In [25]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df2.loc[[0, 1]]

In [ ]:
#Selecting subests of rows and column

In [28]:
df.loc[[0, 1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [30]:
df2.loc[[2, 3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [ ]:
#Conditional selections

In [31]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [32]:
df2[df2["Age"] > 30] #select people whose age > 30

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [36]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")] #select people whose age > 30 and city is paris

   Name  Age   City  Salary
1  Anna   34  Paris   70000