In [1]:
import numpy as np 
import pandas as pd

## Find missing data

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data) #np.nan means null or not a number value

In [3]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [6]:
df.isna() #find where value is null

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [12]:
df.isna().sum() #sum of null values in a col

A    1
B    0
C    2
D    3
dtype: int64

In [13]:
df.isna().any() #find cols if they have any null avlues

A     True
B    False
C     True
D     True
dtype: bool

## Removing Missing Data

In [14]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [15]:
df.dropna() #removes row having null values

     A  B    C    D
0  1.0  1  1.0  1.0

In [17]:
df.dropna(thresh=3) #atleast 3 non null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

## Filling the missing data

In [20]:
df.fillna(0) #fill null values with 0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [21]:
values = {'A':0, 'B' : 100, 'C' : 300, 'D' : 400} #specify what data we want to fill
df.fillna(values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [22]:
df.fillna(df.mean()) #fill values with mean values of na

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0